services:
  api:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  web:
    build:
      context: ./frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
